[build]
  publish = "out"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"

# SPA fallback para Next.js - todas as rotas não encontradas vão para index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers para garantir que o cache funcione corretamente
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 